// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Configuración de la barra lateral principal
  billyGcpSidebar: [
    {
      type: 'category',
      label: '🚀 Visión General de Billy',
      collapsible: false,
      items: ['introduccion', 'arquitectura-general'], // Lee directamente de docs/
    },
    {
      type: 'category',
      label: '📂 Procesadores de Datos (Funciones)', // Nombre más preciso
      items: [
        // Lee todos los archivos en docs/funciones/
        {
          type: 'autogenerated',
          dirName: 'funciones', 
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Orquestación (Workflows)',
      items: [
        // Lee el archivo Billy-workflow.md de docs/orquestacion/
        {
          type: 'autogenerated',
          dirName: 'orquestacion', 
        },
      ],
    },
    {
      type: 'category',
      label: '📬 Esquema de Datos y Mensajería',
      // Lee directamente de docs/pubsub-mensajeria.md
      items: ['pubsub-mensajeria'], 
    },
    {
      type: 'category',
      label: '🔒 Seguridad y Configuración GCP',
      // ¡Lee directamente de los archivos en la raíz de docs/!
      items: ['secret-manager', 'seguridad-iam'], 
    },
  ],
};

module.exports = sidebars;